name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 21.5.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: run the code
        run: |
          echo "Running the code..."
          npm i
          npm run build
          ls -lh && pwd
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-feature-${{ hashFiles('package-lock.json') }}
            npm-feature-
            npm-
      - name: Cleanup
        env:
          GH_TOKEN: ${{ github_token }}
        run: |
          echo "Cleanup step"
          gh extension install actions/gh-actions-cache
          # Extract the last two cache keys
          lastTwoCacheKeys=$(echo "$cacheKeysForPR" | tail -n 2)
          echo "Deleting caches except the last two..."
          for cacheKey in $cacheKeysForPR
          do
              if [[ ! "$lastTwoCacheKeys" =~ "$cacheKey" ]]; then
                  gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
              fi
          done
          echo "Done"
